apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      restartPolicy: Always
      volumes:
      - name: postgres-persistent-storage
        hostPath:
          path: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: postgres:12
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-persistent-storage
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
