apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-sa
  namespace: kube-public
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["traefik.containo.us"]
    resources:
      - "middlewaretcps"
      - "ingressroutes"
      - "middlewares"
      - "tlsoptions"
      - "traefikservices"
      - "tlsstores"
      - "ingressrouteudps"
      - "serverstransports"
      - "ingressroutetcps"
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-role
subjects:
  - kind: ServiceAccount
    name: traefik-sa
    namespace: kube-public